# Load graph & app
twitter = loadgraph("$GRAPE_TEST/twitter.yaml")
sssp = loadapp("$GRAPE_TEST/sssp.yaml")

# Input query
sssp.query(4, "4")

# Unload app & graph
unloadapp(sssp)
unloadgraph(twitter)

# Finally exit
exit
