
twitter_io_all = loadgraph("grape-test/twitter_io/all/twitter-4frag.yaml")
twitter_io_all.extend(grape-test/twitter_io/all/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_all_4")
unloadgraph(twitter_io_all)
unloadapp(sssp_io)

twitter_io_all_sim = loadgraph("grape-test/twitter_io/all/twitter-sim-4frag.yaml")
twitter_io_all_sim.extend(grape-test/twitter_io/all/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_all_4")
unloadgraph(twitter_io_all_sim)
unloadapp(sim_io)

twitter_io_half = loadgraph("grape-test/twitter_io/half/twitter-4frag.yaml")
twitter_io_half.extend(grape-test/twitter_io/half/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_half_4")
unloadgraph(twitter_io_half)
unloadapp(sssp_io)

twitter_io_half_sim = loadgraph("grape-test/twitter_io/half/twitter-sim-4frag.yaml")
twitter_io_half_sim.extend(grape-test/twitter_io/half/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_half_4")
unloadgraph(twitter_io_half_sim)
unloadapp(sim_io)

twitter_io_none = loadgraph("grape-test/twitter_io/none/twitter-4frag.yaml")
twitter_io_none.extend(grape-test/twitter)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_none_4")
unloadgraph(twitter_io_none)
unloadapp(sssp_io)

twitter_io_none_sim = loadgraph("grape-test/twitter_io/none/twitter-sim-4frag.yaml")
twitter_io_none_sim.extend(grape-test/twitter)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_none_4")
unloadgraph(twitter_io_none_sim)
unloadapp(sim_io)

twitter_io_all1 = loadgraph("grape-test/twitter_io/all/twitter-1frag.yaml")
twitter_io_all1.extend(grape-test/twitter_io/all/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_all_1")
unloadgraph(twitter_io_all1)
unloadapp(sssp_io)

twitter_io_all_sim1 = loadgraph("grape-test/twitter_io/all/twitter-sim-1frag.yaml")
twitter_io_all_sim1.extend(grape-test/twitter_io/all/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_all_1")
unloadgraph(twitter_io_all_sim1)
unloadapp(sim_io)

twitter_io_half1 = loadgraph("grape-test/twitter_io/half/twitter-1frag.yaml")
twitter_io_half1.extend(grape-test/twitter_io/half/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_half_1")
unloadgraph(twitter_io_half1)
unloadapp(sssp_io)

twitter_io_half_sim1 = loadgraph("grape-test/twitter_io/half/twitter-sim-1frag.yaml")
twitter_io_half_sim1.extend(grape-test/twitter_io/half/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_half_1")
unloadgraph(twitter_io_half_sim1)
unloadapp(sim_io)

twitter_io_none1 = loadgraph("grape-test/twitter_io/none/twitter-1frag.yaml")
twitter_io_none1.extend(grape-test/twitter)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_none_1")
unloadgraph(twitter_io_none1)
unloadapp(sssp_io)

twitter_io_none_sim1 = loadgraph("grape-test/twitter_io/none/twitter-sim-1frag.yaml")
twitter_io_none_sim1.extend(grape-test/twitter)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_none_1")
unloadgraph(twitter_io_none_sim1)
unloadapp(sim_io)

twitter_io_all2 = loadgraph("grape-test/twitter_io/all/twitter-2frag.yaml")
twitter_io_all2.extend(grape-test/twitter_io/all/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_all_2")
unloadgraph(twitter_io_all2)
unloadapp(sssp_io)

twitter_io_all_sim2 = loadgraph("grape-test/twitter_io/all/twitter-sim-2frag.yaml")
twitter_io_all_sim2.extend(grape-test/twitter_io/all/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_all_2")
unloadgraph(twitter_io_all_sim2)
unloadapp(sim_io)

twitter_io_half2 = loadgraph("grape-test/twitter_io/half/twitter-2frag.yaml")
twitter_io_half2.extend(grape-test/twitter_io/half/extend)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_half_2")
unloadgraph(twitter_io_half2)
unloadapp(sssp_io)

twitter_io_half_sim2 = loadgraph("grape-test/twitter_io/half/twitter-sim-2frag.yaml")
twitter_io_half_sim2.extend(grape-test/twitter_io/half/extend)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_half_2")
unloadgraph(twitter_io_half_sim2)
unloadapp(sim_io)

twitter_io_none2 = loadgraph("grape-test/twitter_io/none/twitter-2frag.yaml")
twitter_io_none2.extend(grape-test/twitter)
sssp_io = loadapp("grape-test/twitter_io/sssp_io.yaml")
sssp_io.config("enable_result_output", true)
sssp_io.query(4, "sssp_io_none_2")
unloadgraph(twitter_io_none2)
unloadapp(sssp_io)

twitter_io_none_sim2 = loadgraph("grape-test/twitter_io/none/twitter-sim-2frag.yaml")
twitter_io_none_sim2.extend(grape-test/twitter)
sim_io = loadapp("grape-test/twitter_io/sim_io.yaml")
sim_io.config("enable_result_output", true)
sim_io.query(Graph("grape-test/twitter_io/sim-ptn"), "sim_io_none_2")
unloadgraph(twitter_io_none_sim2)
unloadapp(sim_io)
exit
